id: P41351915
initial_creation_type: input
source_metadata:
  title: Pakchok Dorje Series
  language: bo
  description: 'Texts by and about Sé Pakchok Dorje (sras ''phags mchog rdo rje, 1893–1943),
    a mind emanation of Jamyang Khyentse Wangpo (1820–1892) and one of the six sons
    of Tokden Śākya Śrī (1853–1919):'
  volume:
    ba92e89267054346918543829ed71ead:
      title: Prayer to Sé Pakchok Dorje
      parent: Prayers
created_at: '2022-03-01T01:09:28.986604'
last_modified_at: '2022-03-01T01:09:28.986607'
